### ISSUE TITLE
JSX syntax highlighting not working 

### ISSUE THREAD

**Issue by jhonGriGi** [JoosepAlviste/palenightfall.nvim#1]
![jsxSyntax](https://user-images.githubusercontent.com/78809587/156860584-25c3b69b-eb8a-4f15-95a8-3451f00fd166.png)

**Comment by JoosepAlviste** [comment]
Hey @jhonGriGi, thanks for raising the issue! Are you using treesitter?

This theme is very reliant on treesitter and I haven't put any effort into supporting regex based JSX highlighting. I should probably write this into the README as well.

**Comment by jhonGriGi** [comment]
hi @JoosepAlviste, I have tried using vim-polyglot, treesitter, vim-jsx-pretty and vim-tsx, but still not working, although my neovim's config is in vimscript, I will try with lua

**Comment by JoosepAlviste** [comment]
@jhonGriGi Using Lua for configuration shouldn't affect this plugin at all, so keep using vimscript if you like. Could you try treesitter one more time and share a screenshot of how the tree looks like with https://github.com/nvim-treesitter/playground? Just to make sure that treesitter is correctly set up with JSX.

Also, are you enabling the colorscheme with `colorscheme palenightfall`? I haven't tried that in a while, I can double check that it still works soon 😄

**Comment by jhonGriGi** [comment]
## Angular
![image](https://user-images.githubusercontent.com/78809587/156966018-6991cac6-6668-4099-8a06-c51b562afa06.png)

the [const] word has a bug, angular code ->
![image](https://user-images.githubusercontent.com/78809587/156967143-e2108a67-3fbe-4dca-8c1d-1eac1cb925da.png)


## React is working
![image](https://user-images.githubusercontent.com/78809587/156966153-dbaee2a9-1213-4e8d-9e7f-8a962a367bc4.png)

if you want, I could try with Vue Js

**Comment by JoosepAlviste** [comment]
Great that React started working, how did you get it working?

The Angular example (TypeScript file) seems to have some weird highlights that I'm not seeing in my TypeScript files (e.g., `import` and `from` are pink). Could you make sure that you're using Treesitter in TypeScript files as well? With the Playground plugin? If yes, could you show the syntax tree from the playground?

**Comment by jhonGriGi** [comment]
I don't have idea why React is working, I just update the plugin with :PackerSync lol

I just did a :TSUpdateSync and my typescript files are working again, so I think de issue is close now.

## Angular examples
![image](https://user-images.githubusercontent.com/78809587/157264506-cf771bb8-3073-48f9-9573-9bf02b040183.png)

![image](https://user-images.githubusercontent.com/78809587/157264633-9a1987fc-1a16-424c-9056-bfded709bb91.png)

**Comment by JoosepAlviste** [comment]
Interesting, I guess it's possible that you had some problems with Treesitter 😄 

But good to see that you got it working! I'll close the issue now.
