### ISSUE TITLE
question: statusline on screenshot

### ISSUE THREAD

**Issue by jakubjun** [JoosepAlviste/palenightfall.nvim#4]
hello, can i ask what plugin/config is responsible for the statusline in the example screenshot?

![image](https://user-images.githubusercontent.com/40307291/213882293-0af09d49-c754-41eb-8bd4-e69492ed7a54.png)

**Comment by JoosepAlviste** [comment]
Hey!

This is my own statusline, not using any plugins. You can find the implementation in my dotfiles:

- The statusline code: https://github.com/JoosepAlviste/dotfiles/blob/9d5e686f497b08af98bd9579ec0c9f31fc48837c/config/nvim/lua/j/statusline.lua
- Some extra highlights for the colors: https://github.com/JoosepAlviste/dotfiles/blob/master/config/nvim/lua/j/plugins/palenightfall.lua#L7
- The filetype icons are from nerd fonts, and some from [nonicons](https://github.com/yamatsum/nonicons)

**Comment by Sirikakire** [comment]
May i ask what is your font u were using as screenshot demos?

**Comment by JoosepAlviste** [comment]
Hey! I think that on the first screenshot in the README, it's Iosevka, and on the others it might be Fira Code, but not 100% sure.
